name            = "Clear Hud Rewrite v0.0.0";                    // Name of your mod
author          = "Clear Hud Rewrite Team";                // Affects Arma 3 Launcher, when the mod are loaded as local
logo            = "img\chr_icon.paa";            // Logo displayed in the main menu
logoOver        = "img\chr_icon.paa";    // When the mouse is over, in the main menu
tooltip         = "Clear Hud Rewrite";
tooltipOwned    = "by Clear Hud Rewrite Team";                // Tool tip displayed when the mouse is left over, in the main menu
picture         = "img\chr_logo.paa";        // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName      = "GitHub";
action          = "hchrps://github.com/TacticalTrainingTeam/clear-hud-rewrite";            // Website URL, that can be accessed from the expansions menu
overview        = "Hide chat unless you need it.";    // Supports structured text
hideName        = 0;                        // Hide the extension name
hidePicture     = 0;                        // Hide the extension menu
dlcColor[]      = { 0.23, 0.39, 0.30, 1 };    // Color used for DLC stripes and backgrounds (RGBA)
logoSmall       = "img\chr_icon.paa";        // Display in creative lists, next to the entities added by the mod